// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DataStaging.Models;

namespace DataStaging.Data
{
    public partial class AppDBContext : DbContext
    {
        public AppDBContext()
        {
        }

        public AppDBContext(DbContextOptions<AppDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DataLeadHeader> DataLeadHeaders { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Thai_100_CS_AI");

            modelBuilder.Entity<DataLeadHeader>(entity =>
            {
                entity.Property(e => e.DataLeadHeaderId)
                    .ValueGeneratedNever()
                    .HasComment("รหัสแคมเปญ (UUID)");

                entity.Property(e => e.CreatedByUserId).HasComment("รหัสผู้สร้าง");

                entity.Property(e => e.CreatedDate).HasComment("วันที่สร้าง");

                entity.Property(e => e.DataLeadHeaderCode).HasComment("\"รหัสอ้างอิงของแคมเปญ (อาจเป็นรหัสที่คนกำหนด เช่น CMP68000003 \nCMP + YY[68] + Running รอบการนำเข้า 6 digit)\"");

                entity.Property(e => e.DataLeadHeaderName).HasComment("ชื่อแคมเปญ");

                entity.Property(e => e.DataLeadHeaderStatusId).HasComment("สถานะปัจจุบันของ LeadHeader");

                entity.Property(e => e.DataLeadHeaderTypeId).HasComment("รหัสประเภทแคมเปญ เช่น birthday");

                entity.Property(e => e.ItemCount).HasComment("จำนวน Lead ที่อยู่ในแคมเปญนี้");

                entity.Property(e => e.UpdatedByUserId).HasComment("รหัสผู้อัพเดท");

                entity.Property(e => e.UpdatedDate).HasComment("วันที่อัพเดท");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}