// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataStaging.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataStaging.Data
{
    public partial interface IAppDBContextProcedures
    {
        Task<List<usp_DataLeadBirthday_InsertResult>> usp_DataLeadBirthday_InsertAsync(DateTime? BirthDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
