// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataStaging.Models
{
    [Table("DataLeadHeader")]
    public partial class DataLeadHeader
    {
        /// <summary>
        /// รหัสแคมเปญ (UUID)
        /// </summary>
        [Key]
        public Guid DataLeadHeaderId { get; set; }
        /// <summary>
        /// &quot;รหัสอ้างอิงของแคมเปญ (อาจเป็นรหัสที่คนกำหนด เช่น CMP68000003 
        /// CMP + YY[68] + Running รอบการนำเข้า 6 digit)&quot;
        /// </summary>
        [StringLength(20)]
        [Unicode(false)]
        public string DataLeadHeaderCode { get; set; }
        /// <summary>
        /// ชื่อแคมเปญ
        /// </summary>
        [StringLength(255)]
        public string DataLeadHeaderName { get; set; }
        /// <summary>
        /// จำนวน Lead ที่อยู่ในแคมเปญนี้
        /// </summary>
        public int? ItemCount { get; set; }
        /// <summary>
        /// รหัสประเภทแคมเปญ เช่น birthday
        /// </summary>
        public int? DataLeadHeaderTypeId { get; set; }
        /// <summary>
        /// สถานะปัจจุบันของ LeadHeader
        /// </summary>
        public int? DataLeadHeaderStatusId { get; set; }
        public bool? IsActive { get; set; }
        /// <summary>
        /// วันที่สร้าง
        /// </summary>
        public DateTime? CreatedDate { get; set; }
        /// <summary>
        /// รหัสผู้สร้าง
        /// </summary>
        public int? CreatedByUserId { get; set; }
        /// <summary>
        /// วันที่อัพเดท
        /// </summary>
        public DateTime? UpdatedDate { get; set; }
        /// <summary>
        /// รหัสผู้อัพเดท
        /// </summary>
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ReferenceDate { get; set; }
    }
}