// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataStaging.Models
{
    public partial class usp_DataLeadBirthday_InsertResult
    {
        public bool? IsResult { get; set; }
        public string? Result { get; set; }
        public string? Msg { get; set; }
    }
}
